[package]
name = "orbit_game"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.57"
features = [
  'CanvasRenderingContext2d',
]

[lib]
crate-type = ["cdylib"]
